build:
	@echo Running Build
	docker build . -t us-central1-docker.pkg.dev/devbookhq/devbook-runner-templates/base

push:
	@echo Running push
	docker push us-central1-docker.pkg.dev/devbookhq/devbook-runner-templates/base
